### ISSUE TITLE
How was you able to generate the flights.proto file

### ISSUE THREAD

**Issue by moaaztaha** [AWeirdDev/flights#10]
Hello, found your repo today and I just want to say really nice work 👍 

I've been searching for a while now online but can't find any resource about that, specially generating the .proto files to use.

**Comment by AWeirdDev** [comment]
Hi there,

In the README, I mentioned that I used [protobuf-decoder.netlify.app](https://protobuf-decoder.netlify.app/) which comes in handy when decoding this data.

![image](https://github.com/user-attachments/assets/276de766-e870-4690-988f-9b210b8aab57)

I then tried to understand the meaning behind each value (which is "inferring" or "guessing") and they worked!

Best

**Comment by moaaztaha** [comment]
Ok thanks
