### ISSUE TITLE
No flights found

### ISSUE THREAD

**Issue by LetThereBeQE** [AWeirdDev/flights#17]
Hi, getting error:
RuntimeError: No flights found. (preflight checked)
Possible reasons:
- Invalid query (e.g., date is in the past or cannot be booked)
- Invalid airport

Am getting this for a very simplified version of the readme code for a flight I am certain exists.
Any idea what might be wrong?

> `from fast_flights import FlightData, Passengers, create_filter, get_flights
> 
> filter = create_filter(
>     flight_data=[
>         # Include more if it's not a one-way trip
>         FlightData(
>             date="2024-11-15",  # Date of departure
>             from_airport="LAX", 
>             to_airport="SFO"
>         ),
>         # ... include more for round trips
>     ],
>     trip="one-way",  # Trip (round-trip, one-way)
>     seat="economy",  # Seat (economy, premium-economy, business or first)
>     passengers=Passengers(
>         adults=1,
>     ),
> )
> 
> result = get_flights(filter)
> 
> print("The price is currently", result.current_price)`

**Comment by jack-ireland** [comment]
It could be an issue with cookies. I ran while using a VPN - putting me in the US - and it worked for me.
