### ISSUE TITLE
Question - Have you implemented a way to get the actual price?

### ISSUE THREAD

**Issue by JobeOneKenobi** [AWeirdDev/flights#5]
Thought you mentioned you were working on that, just checking if it happened to be implemented yet, didn't see it in the readme. Thought you might have added it with 1.3.

If not is it something you plan to add? Any tips for me on how to find it? I tried a little but didnt get far, I found prices / dollar amounts in the text extract but it was pretty random not very coorelated with the actual ticket prices.

Appreciate it!

Joseph

P.S. I'll be testing if 1.3 solved those other bugs this weekend, thx for releasing it.

**Comment by AWeirdDev** [comment]
Hi,

Yes, I suppose. I think I've added the "price" schema along some recent updates as mentioned in this commit: https://github.com/AWeirdDev/flights/commit/b094b39de6e5a68ef5abf843ffa4a2427787b7f2

Cheers,
AWeirdDev

**Comment by d2x** [comment]
There's a typo in the classes used for obtaining the price. I've submitted PR https://github.com/AWeirdDev/flights/pull/7 which resolves it.
