### ISSUE TITLE
Question - proxy?

### ISSUE THREAD

**Issue by lkward13** [AWeirdDev/flights#6]
Does this use a proxy? I'd like to scrape a lot, but don't want to get banned.

**Comment by lkward13** [comment]
I'll do that, thank you!

If you ever do any paid contract work, I have a project I'd like to discuss that needs something built very similar to this. hit me up on twitter @lkward13

**Comment by AWeirdDev** [comment]
You're welcome! Cheers.

**Comment by ziyedbe** [comment]
Proxies are not working for me : 
`TypeError: get_flights() got an unexpected keyword argument 'proxies'`

**Comment by AWeirdDev** [comment]
> Proxies are not working for me : `TypeError: get_flights() got an unexpected keyword argument 'proxies'`

This issue is for the older version of this project. It seems like proxies are not yet available? I need to check.
